name: Flutter CI

on:
  push:
    branches:
      - generate-apk  # Replace with your branch name
  pull_request:
    branches:
      - generate-apk  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Replace with your Flutter version

      - name: Install dependencies
        run: flutter pub get


      - name: Build APK
        run: flutter build apk --flavor dev

      - name: List build directory (debugging step)
        run: ls -R build/app/outputs/flutter-apk/


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-dev-release.apk
          path: build/app/outputs/flutter-apk/app-dev-release.apk
